import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Hero from "@/components/ui/Hero";
import SpaIntroSection from "@/components/ui/SpaIntroSection";
import StarFormulasSection from "../components/ui/StarFormulasSection";
import HomeBlogSection from "@/components/ui/blog/HomeBlogSection";
import globalVariables from "@/config/globalVariables";
import InfiniteSlider from "@/components/ui/InfiniteSlider";
import TestimonialsSection from "@/components/ui/TestimonialsSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({ 
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title> Accueil | {globalVariables.siteName} </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        
      >
        <Hero />
        <main className={styles.main}>
         <SpaIntroSection/>
         <StarFormulasSection/>
         <TestimonialsSection />
         {/*<HomeBlogSection/>*/}
         <InfiniteSlider/>
        </main>
       
      </div>
    </>
  );
}
